# Generated by Django 3.2.20 on 2023-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
